const mongoose = require('mongoose');

const fileSchema = new mongoose.Schema(
  {
    key: { type: String, required: true },
    name: { type: String, required: true },
    mime: { type: String, required: true },
    size: { type: Number, required: true },
  },
  { _id: false }
);

const billSchema = new mongoose.Schema(
  {
    payer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    organization: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Organization',
      index: true,
    },
    organizationName: { type: String, default: '' },
    category: {
      type: String,
      required: [true, 'Category is required'],
      enum: [
        'Religious Donation',
        'Municipal Corporation',
        'Vehicle',
        'Income Tax',
        'GST',
        'Utility Bills',
        'Education',
        'Fine/Penalty',
        'Other',
      ],
      index: true,
    },
    subType: { type: String, default: '' },
    type: { type: String, default: '', maxlength: 60 },
    department: { type: String, default: '' },
    religion: { type: String, enum: ['', 'Hindu', 'Muslim', 'Christian', 'Sikh', 'Buddhist', 'Jain', 'Other'], default: '' },
    amount: { type: Number, required: true, min: 0 },
    date: { type: Date, required: true, index: true },
    referenceNumber: { type: String, default: '' },
    paymentGateway: { type: String, default: '' },
    payeeLocation: { type: String, default: '' },
    notes: { type: String, default: '', maxlength: 1000 },
    files: { type: [fileSchema], default: [] },
    status: {
      type: String,
      enum: ['pending', 'approved', 'rejected'],
      default: 'pending',
      index: true,
    },
    reviewNote: { type: String, default: '' },
    reviewedAt: { type: Date },
    reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    autoGenerated: { type: Boolean, default: false },
    sourcePayment: { type: mongoose.Schema.Types.ObjectId, ref: 'Payment' },
  },
  { timestamps: true }
);

billSchema.index({ payer: 1, date: -1 });
billSchema.index({ organization: 1, status: 1 });
billSchema.index({ category: 1, date: -1 });

module.exports = mongoose.model('Bill', billSchema);
