const Payment = require('../models/Payment');
const Organization = require('../models/Organization');
const Bill = require('../models/Bill');
const User = require('../models/User');
const storage = require('./storage');
const { buildReceiptPdf } = require('./receiptPdf');
const { runInTransaction } = require('../utils/transaction');

function nextReceiptNumber() {
  return `DB-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}-${Math.floor(Math.random() * 900 + 100)}`;
}

/**
 * Generate and upload the PDF receipt for a payment.
 */
async function generateReceipt(payment, payer, organization) {
  const pdfBuffer = await buildReceiptPdf({
    receipt: payment,
    payer,
    organization,
    files: [],
  });
  return storage.upload({
    buffer: pdfBuffer,
    originalName: `receipt-${payment.receiptNumber}.pdf`,
    mime: 'application/pdf',
    folder: 'receipts',
    kind: 'pdf',
  });
}

/**
 * Finalize a payment end-to-end, atomically:
 *   1. mark the payment completed (+ receipt number / timestamp)
 *   2. increment the organization's totalReceived
 *   3. create the auto-approved bill and link it to the payment
 *   4. upload the generated PDF receipt
 *
 * Idempotent: if the payment is already completed it returns the existing
 * artifacts without re-applying any money movement. This makes it safe for
 * both the interactive verification endpoint and the Razorpay webhook
 * (including retries).
 *
 * @param {string} paymentId
 * @returns {Promise<{payment: import('mongoose').Document, bill: import('mongoose').Document|null, receiptUrl: string}>}
 */
async function finalizePayment({ paymentId }) {
  const payment = await Payment.findById(paymentId);
  if (!payment) {
    const err = new Error('Payment not found');
    err.statusCode = 404;
    throw err;
  }
  if (payment.status === 'completed') {
    const bill = payment.bill ? await Bill.findById(payment.bill) : null;
    return { payment, bill, receiptUrl: '' };
  }

  const [org, payer] = await Promise.all([
    Organization.findById(payment.organization),
    User.findById(payment.payer),
  ]);
  if (!org) {
    const err = new Error('Organization not found');
    err.statusCode = 400;
    throw err;
  }

  payment.receiptNumber = payment.receiptNumber || nextReceiptNumber();
  const { key: receiptPdf } = await generateReceipt(payment, payer, org);

  const { bill } = await runInTransaction(async (session) => {
    const opts = session ? { session } : {};

    const fresh = session
      ? await Payment.findOne({ _id: payment._id, status: 'pending' }).session(session)
      : payment;

    if (!fresh) {
      // Concurrency: another request already finalized this payment.
      const existing = await Payment.findById(payment._id);
      const existingBill = existing && existing.bill ? await Bill.findById(existing.bill) : null;
      return { bill: existingBill };
    }

    fresh.status = 'completed';
    fresh.receiptPdf = receiptPdf;
    fresh.completedAt = fresh.completedAt || new Date();
    await fresh.save(opts);

    await Organization.updateOne(
      { _id: payment.organization },
      { $inc: { totalReceived: payment.amount } },
      opts
    );

    const [created] = await Bill.create(
      [
        {
          payer: payment.payer,
          organization: payment.organization,
          organizationName: payment.organizationName,
          category: 'Religious Donation',
          amount: payment.amount,
          date: fresh.completedAt,
          status: 'approved',
          autoGenerated: true,
          sourcePayment: payment._id,
          referenceNumber: payment.receiptNumber,
        },
      ],
      opts
    );

    fresh.bill = created._id;
    await fresh.save(opts);
    return { bill: created };
  });

  return { payment: await Payment.findById(payment._id), bill, receiptUrl: '' };
}

module.exports = { finalizePayment, nextReceiptNumber };
