const PDFDocument = require('pdfkit');
const { PassThrough } = require('stream');

function streamToBuffer(stream) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    stream.on('data', (c) => chunks.push(c));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
  });
}

function buildReceiptPdf({ receipt, payer, organization, files, downloadUrl }) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const stream = new PassThrough();
  doc.pipe(stream);

  const now = new Date();
  const money = (n) => `₹${Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const d = (x) => (x ? new Date(x).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '-');

  doc
    .rect(0, 0, doc.page.width, 70)
    .fill('#1a3a5c');
  doc
    .fill('#ffffff')
    .fontSize(20)
    .text('DONATE BHARAT', 50, 20, { align: 'center' })
    .fontSize(10)
    .text('Digital Payment & Record-Keeping Platform', { align: 'center' });

  doc.moveDown(1.5);
  doc
    .fill('#1a3a5c')
    .fontSize(16)
    .text('Payment Receipt', { align: 'center' });
  doc
    .fill('#333')
    .fontSize(9)
    .text(`Receipt No: ${receipt.receiptNumber || '-'}    Date: ${d(now)}`, { align: 'center' });

  doc.moveDown(2);
  doc.fontSize(10);
  const labelW = 130;
  const drawRow = (label, value, bold = false) => {
    doc
      .font('Helvetica-Bold')
      .fill('#555')
      .text(label, 50, doc.y, { width: labelW, continued: true })
      .font(bold ? 'Helvetica-Bold' : 'Helvetica')
      .fill('#111')
      .text(value || '-', { width: doc.page.width - 50 - labelW - 20 });
    doc.moveDown(0.6);
  };

  drawRow('Received From:', payer ? payer.name : '-');
  drawRow('Payer Email:', payer ? payer.email : '-');
  drawRow('Payee:', organization ? organization.name : receipt.organizationName || '-');
  drawRow('Religion:', organization ? organization.religion : '-');
  drawRow('Purpose:', receipt.purpose || '-');
  drawRow('Payment Mode:', receipt.paymentMode || '-');
  drawRow('Transaction ID:', receipt.razorpayPaymentId || '-');
  drawRow('Reference:', receipt.referenceNumber || '-');

  doc.moveDown(1);
  doc
    .rect(50, doc.y, doc.page.width - 100, 40)
    .fill('#f1f5f9');
  doc
    .fill('#1a3a5c')
    .font('Helvetica-Bold')
    .fontSize(13)
    .text('AMOUNT PAID', 70, doc.y + 8)
    .fontSize(16)
    .fill('#0b7a3b')
    .text(money(receipt.amount), 70, doc.y + 3, { align: 'right', width: doc.page.width - 140 });
  doc.moveDown(1.5);

  doc
    .fill('#666')
    .fontSize(9)
    .text(`Status: ${(receipt.status || 'completed').toUpperCase()}`, 50, doc.y)
    .moveDown(0.5)
    .text(`Generated automatically on ${now.toLocaleString('en-IN')}. This is a valid digital receipt.`, 50, doc.y);

  if (files && files.length) {
    doc.moveDown(1);
    doc.fill('#333').font('Helvetica-Bold').fontSize(10).text('Attached Documents');
    files.forEach((f) => {
      doc.font('Helvetica').fontSize(9).fill('#555').text(`  • ${f.name}`);
    });
  }

  if (downloadUrl) {
    doc
      .moveDown(1)
      .fill('#888')
      .fontSize(8)
      .text(downloadUrl, 50, doc.y, { width: doc.page.width - 100 });
  }

  doc
    .moveDown(1.5)
    .font('Helvetica-Oblique')
    .fill('#999')
    .fontSize(8)
    .text('This receipt was digitally generated by Donate Bharat. No physical copy required.', { align: 'center' });

  doc.end();
  return streamToBuffer(stream);
}

module.exports = { buildReceiptPdf, streamToBuffer };
